### ISSUE TITLE
Pair dataset generation for histograms is invalid

### ISSUE THREAD

**Issue by mpancia** [cmla-psu/statdp#3]
I may be misunderstanding something, but it seems to me that the candidate data pair generation for histogram queries is not valid. 

As mentioned in the paper, only the "one-below" and "one-above" inputs correspond to histograms coming from L_1-adjacent databases. In the code 
https://github.com/cmla-psu/statdp/blob/696e0a81bdbcd7051617f799818d9c8a7111717f/statdp/generators.py#L44 
however, all the other simple input vectors are generated, which do not correspond to histograms from adjacent databases. This might lead to false positives for detecting privacy violations.

Anyways, thanks for this -- the paper is neat.

**Comment by yuxincs** [comment]
Hi @mpancia, that's a good point and thanks for pointing it out.

I think at first we wanted to make the database generator to be general enough. Maybe we should add an argument in `generate_databases` to restrict that specifically for algorithms like histogram. Anyways, good news is that the final counterexamples generated for histogram are valid.

Actually the database generator we designed is fairly simple and more future work can be done to make it better :).
